version: "3"
services:
  app:
    depends_on:
      - mongodb
    container_name: app_server
    build:
      context: .
      dockerfile: Dockerfile
    image: app_server
    ports:
    - 1337:1337
  mongodb:
    image: mongo
    volumes:
    - ./mongodb/database:/data/db
    ports:
    - 27017:27017

