spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projeto2?useSSL=false
    username: projeto2
    password: projeto2
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC