version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "chatdb"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volumes/data/:/var/lib/mysql
      - ./docker/init:/docker-entrypoint-initdb.d
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge